
FIND_PATH(XERCES_INCLUDES xercesc/dom/DOM.hpp
  HINTS
  ${XERCES_INCLUDE_DIR}
  $ENV{XERCES_INCLUDE_DIR}
  /usr
  PATH_SUFFIXES include
)

FIND_LIBRARY(XERCES_LIB xerces-c
  HINTS
  ${XERCES_LIB_DIR}
  $ENV{XERCES_LIB_DIR}
  /usr
  PATH_SUFFIXES lib
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(XercesC DEFAULT_MSG XERCES_LIB XERCES_INCLUDES)

